apiVersion: v1
kind: Template
labels:
  template: service-registry-template
metadata:
  annotations:
    description: service registry
    iconClass: icon-spring
    tags: java,spring
    version: 1.0.0
  name: service-registry-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: service-registry
  spec:
    replicas: 1
    selector:
      deploymentconfig: service-registry
    strategy:
      # We set the type of strategy to Recreate, which means that it will be scaled down prior to being scaled up
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: service-registry
      spec:
        containers:
        - image: vaanay/service-registry
          name: service-registry
          ports:
          - containerPort: 8761
            protocol: TCP
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
         - service-registry
        from:
          kind: ImageStreamTag
          name: spring-n-app:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    name: service-registry
  spec:
    to:
      kind: Service
      name: service-registry
- apiVersion: v1
  kind: Service
  metadata:
    name: service-registry
  spec:
    ports:
    - port: 8761
      targetPort: 8761
    selector:
      deploymentconfig: service-registry


