apiVersion: v1
kind: DeploymentConfig
metadata:
  name: shoppingcart-ui
  labels:
    app: shoppingcart-ui
    version: v1
spec:
    replicas: 1
    selector:
      deploymentconfig: shoppingcart-ui
    strategy:
      # We set the type of strategy to Recreate, which means that it will be scaled down prior to being scaled up
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: shoppingcart-ui
      spec:
        containers:
        - image: vaanay/shoppingcart-ui
          name: shoppingcart-ui
          ports:
          - containerPort: 8080
            protocol: TCP
        initContainers:
          - name: init-order
            image: busybox:1.28
            command: ['sh', '-c', 'wget -c http://order-service:8383/actuator/health']
          - name: init-catalog
            image: busybox:1.28
            command: ['sh', '-c', 'wget -c http://catalog-service:8383/actuator/health']
          - name: init-inventory
            image: busybox:1.28
            command: ['sh', '-c', 'wget -c http://inventory-service:8282/actuator/health']
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingcart-ui
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
      deploymentconfig: shoppingcart-ui
---
apiVersion: v1
kind: Route
metadata:
  name: shoppingcart-ui
spec:
  to:
   kind: Service
   name: shoppingcart-ui
